config/routes.rb
TestfflApp::Application.routes.draw do

  root "static_pages#home"

  get "static_pages/Add_team"

  resources :teamplayers

  resources :fteams

  resources :abbrvs

  resources :live_players

  get 'live_players', to: 'live_players#index' 

end

app/models/abbrv.rb
class Abbrv < ActiveRecord::Base
end

app/controllers/abbrvs_controller.rb
class AbbrvsController < ApplicationController
  before_action :set_abbrv, only: [:show, :edit, :update, :destroy]

  # GET /abbrvs
  # GET /abbrvs.json
  def index
    #system "rake db:reset"
    #system "rake populateA"
    @abbrvs = Abbrv.all.sort
  end

  # GET /abbrvs/1
  # GET /abbrvs/1.json
  def show
  end

  # GET /abbrvs/new
  def new
    @abbrv = Abbrv.new
  end

  # GET /abbrvs/1/edit
  def edit
  end

  # POST /abbrvs
  # POST /abbrvs.json
  def create
    @abbrv = Abbrv.new(abbrv_params)

    respond_to do |format|
      if @abbrv.save
        format.html { redirect_to @abbrv, notice: 'Abbrv was successfully created.' }
        format.json { render action: 'show', status: :created, location: @abbrv }
      else
        format.html { render action: 'new' }
        format.json { render json: @abbrv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abbrvs/1
  # PATCH/PUT /abbrvs/1.json
  def update
    respond_to do |format|
      if @abbrv.update(abbrv_params)
        format.html { redirect_to @abbrv, notice: 'Abbrv was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @abbrv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abbrvs/1
  # DELETE /abbrvs/1.json
  def destroy
    @abbrv.destroy
    respond_to do |format|
      format.html { redirect_to abbrvs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_abbrv
      @abbrv = Abbrv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def abbrv_params
      params.require(:abbrv).permit(:Abrv, :Team)
    end
end

app/helpers/abbrvs_helper.rb
module AbbrvsHelper
end

app/views/abbrvs/_form.html.erb
<%= form_for(@abbrv) do |f| %>
  <% if @abbrv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@abbrv.errors.count, "error") %> prohibited this abbrv from being saved:</h2>

      <ul>
      <% @abbrv.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Abrv %><br>
    <%= f.text_field :Abrv %>
  </div>
  <div class="field">
    <%= f.label :Team %><br>
    <%= f.text_field :Team %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abbrvs/edit.html.erb
<h1>Editing abbrv</h1>

<%= render 'form' %>

<%= link_to 'Show', @abbrv %> |
<%= link_to 'Back', abbrvs_path %>

app/views/abbrvs/index.html.erb
<h1>Listing abbrvs</h1>

<table>
  <thead>
    <tr>
      <th>Abrv</th>
      <th>Team</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @abbrvs.each do |abbrv| %>
      <tr>
        <td><%= abbrv.Abrv %></td>
        <td><%= abbrv.Team %></td>
        <td><%= link_to 'Show', abbrv %></td>
        <td><%= link_to 'Edit', edit_abbrv_path(abbrv) %></td>
        <td><%= link_to 'Destroy', abbrv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Abbrv', new_abbrv_path %>

app/views/abbrvs/new.html.erb
<h1>New abbrv</h1>

<%= render 'form' %>

<%= link_to 'Back', abbrvs_path %>

app/views/abbrvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Abrv:</strong>
  <%= @abbrv.Abrv %>
</p>

<p>
  <strong>Team:</strong>
  <%= @abbrv.Team %>
</p>

<%= link_to 'Edit', edit_abbrv_path(@abbrv) %> |
<%= link_to 'Back', abbrvs_path %>