config/routes.rb
TestfflApp::Application.routes.draw do

  root "static_pages#home"

  get "static_pages/Add_team"

  resources :teamplayers

  resources :fteams

  resources :abbrvs

  resources :live_players

  get 'live_players', to: 'live_players#index' 

end

app/models/live_player.rb
class LivePlayer < ActiveRecord::Base
	#has_many :teamplayers
	has_many :fteams, through:  :teamplayers
	#has_and_belongs_to_many :fteams
end

app/models/liveplayer.rb
class LivePlayer < ActiveRecord::Base
	belongs_to :fteam
	has_many :fteam	
end

app/controllers/live_players_controller.rb
class LivePlayersController < ApplicationController
  before_action :set_live_player, only: [:show, :edit, :update, :destroy]

  # GET /live_players
  # GET /live_players.json
  def index
	  #puts DateTime.now
    #system "rake db:reset"
    #system "rake populateA"
    system "rake populate"
    flash[:notice] = "Players updated"

   if params[:Team]
	@live_players = LivePlayer.where(:Team => params[:Team])
	@cTeam = params[:Team]
   else
	@live_players = LivePlayer.all
   end

    @abbrvs = Abbrv.all
  end

  # GET /live_players/1
  # GET /live_players/1.json
  def show
  end

  # GET /live_players/new
  def new
    @live_player = LivePlayer.new
  end

  # GET /live_players/1/edit
  def edit
  end

  # POST /live_players
  # POST /live_players.json
  def create
    @live_player = LivePlayer.new(live_player_params)

    respond_to do |format|
      if @live_player.save
        format.html { redirect_to @live_player, notice: 'Live player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @live_player }
      else
        format.html { render action: 'new' }
        format.json { render json: @live_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /live_players/1
  # PATCH/PUT /live_players/1.json
  def update
    respond_to do |format|
      if @live_player.update(live_player_params)
        format.html { redirect_to @live_player, notice: 'Live player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @live_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /live_players/1
  # DELETE /live_players/1.json
  def destroy
    @live_player.destroy
    respond_to do |format|
      format.html { redirect_to live_players_url }
      format.json { head :no_content }
    end
  end

  def name_team
	'Plyr Team'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_live_player
      @live_player = LivePlayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def live_player_params
      params.require(:live_player).permit(:Nid, :Plyr, :Team)
    end
end

app/helpers/live_players_helper.rb
module LivePlayersHelper
end

app/views/live_players/_form.html.erb
<%= form_for(@live_player) do |f| %>
  <% if @live_player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@live_player.errors.count, "error") %> prohibited this live_player from being saved:</h2>

      <ul>
      <% @live_player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nid %><br>
    <%= f.number_field :Nid %>
  </div>
  <div class="field">
    <%= f.label :Plyr %><br>
    <%= f.text_field :Plyr %>
  </div>
  <div class="field">
    <%= f.label :Team %><br>
    <%= f.text_field :Team %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/live_players/edit.html.erb
<h1>Editing live_player</h1>

<%= render 'form' %>

<%= link_to 'Show', @live_player %> |
<%= link_to 'Back', live_players_path %>

app/views/live_players/index.html.erb
<h1>Listing All Players</h1>

<div id="progressbar"><div class="progress-label">Loading...</div></div>

<br />

<select id = "FilterTm" style="float:left">
		<option>Select a Team...</option>
	<%# Abbrv.order("Team").each do |abbrv| %>
		<option><%#= abbrv.Team %></option>
		<%# end %>
		<% @abbrvs.each do |abv| %>
		<option><%= abv.Team %></option>
	<% end %>
</select>

<a id="playerBtn"><button type="button" id="plyrBtn" style="float:left">Players</button></a>

<%#= link_to '<button type = "button">Players</button>'.html_safe, live_players_path(:Team => @tmf) %>
<br />
<br />
<br />
<input type="text" class="hiddenField" id="curTeam" />

<br />
<select id = "ptable" size = 30>
	<% @live_players.each do |live_player| %>
		<option><%= live_player.Plyr %></option>
	<% end %>
</select>

<!--
<table id = "ptable" style= float:right>
  <thead>
    <tr>
      <th>Plyr</th>
      <th>Team</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%# @live_players.each do |live_player| %>
      <tr>
        <td><%#= live_player.Plyr %></td>
        <td><%#= live_player.Team %></td>
        <td><%#= link_to 'Show', live_player %></td>
        <td><%#= link_to 'Edit', edit_live_player_path(live_player) %></td>
	<td><%#= link_to 'Destroy', live_player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>
-->
<br>

<%#= link_to 'New Live player', new_live_player_path %>

app/views/live_players/new.html.erb
<h1>New live_player</h1>

<%= render 'form' %>

<%= link_to 'Back', live_players_path %>

app/views/live_players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nid:</strong>
  <%= @live_player.Nid %>
</p>

<p>
  <strong>Plyr:</strong>
  <%= @live_player.Plyr %>
</p>

<p>
  <strong>Team:</strong>
  <%= @live_player.Team %>
</p>

<%= link_to 'Edit', edit_live_player_path(@live_player) %> |
<%= link_to 'Back', live_players_path %>