config/routes.rb
TestfflApp::Application.routes.draw do

  root "static_pages#home"

  get "static_pages/Add_team"

  resources :teamplayers

  resources :fteams

  resources :abbrvs

  resources :live_players

  get 'live_players', to: 'live_players#index' 

end

app/models/fteam.rb
class Fteam < ActiveRecord::Base
	#belongs_to :liveplayer
	has_many :teamplayers
	has_many :live_players, through: :teamplayers
	#has_and_belongs_to_many :liveplayers
end

app/controllers/fteams_controller.rb
class FteamsController < ApplicationController
  before_action :set_fteam, only: [:show, :edit, :update, :destroy]

  # GET /fteams
  # GET /fteams.json
  def index
    @fteams = Fteam.all
   #@teamplayers = Teamplayer.all
  end

  # GET /fteams/1
  # GET /fteams/1.json
  def show
  end

  # GET /fteams/new
  def new
    @fteam = Fteam.new
  end

  # GET /fteams/1/edit
  def edit
  end

  # POST /fteams
  # POST /fteams.json
  def create
    @fteam = Fteam.new(fteam_params)

    respond_to do |format|
      if @fteam.save
        format.html { redirect_to @fteam, notice: 'Fteam was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fteam }
      else
        format.html { render action: 'new' }
        format.json { render json: @fteam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fteams/1
  # PATCH/PUT /fteams/1.json
  def update
    respond_to do |format|
      if @fteam.update(fteam_params)
        format.html { redirect_to @fteam, notice: 'Fteam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fteam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fteams/1
  # DELETE /fteams/1.json
  def destroy
    @fteam.destroy
    respond_to do |format|
      format.html { redirect_to fteams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fteam
      @fteam = Fteam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fteam_params
      params.require(:fteam).permit(:Team, :TeamUrl)
    end
end

app/helpers/fteams_helper.rb
module FteamsHelper
end

app/views/fteams/_form.html.erb
<%= form_for(@fteam) do |f| %>
  <% if @fteam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fteam.errors.count, "error") %> prohibited this fteam from being saved:</h2>

      <ul>
      <% @fteam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Team %><br>
    <%= f.text_field :Team %>
  </div>
  <div class="field">
    <%= f.label :TeamUrl %><br>
    <%= f.text_field :TeamUrl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fteams/edit.html.erb
<h1>Editing fteam</h1>

<%= render 'form' %>

<%= link_to 'Show', @fteam %> |
<%= link_to 'Back', fteams_path %>

app/views/fteams/index.html.erb
<h1>Listing fteams</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Teamurl</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fteams.each do |fteam| %>
      <tr>
        <td><%= fteam.Team %></td>
        <td><%= fteam.TeamUrl %></td>
        <td><%= link_to 'Show', fteam %></td>
        <td><%= link_to 'Edit', edit_fteam_path(fteam) %></td>
        <td><%= link_to 'Destroy', fteam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fteam', new_fteam_path %>

app/views/fteams/new.html.erb
<h1>New fteam</h1>

<%= render 'form' %>

<%= link_to 'Back', fteams_path %>

app/views/fteams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @fteam.Team %>
</p>

<p>
  <strong>Teamurl:</strong>
  <%= @fteam.TeamUrl %>
</p>

<%= link_to 'Edit', edit_fteam_path(@fteam) %> |
<%= link_to 'Back', fteams_path %>