config/routes.rb
TestfflApp::Application.routes.draw do

  root "static_pages#home"

  get "static_pages/Add_team"

  resources :teamplayers

  resources :fteams

  resources :abbrvs

  resources :live_players

  get 'live_players', to: 'live_players#index' 

end

app/models/teamplayer.rb
class Teamplayer < ActiveRecord::Base
	belongs_to :live_player
	belongs_to :fteam
        delegate :Plyr, to: :live_player
	delegate :Team, to: :live_player
	delegate :Nid, to: :live_player
	delegate :name_team, to: :live_player
	delegate :fanteam, to: :fteam

end

app/controllers/teamplayers_controller.rb
class TeamplayersController < ApplicationController
        before_filter :set_id
      	before_action :set_id, :set_teamplayer, only: [:show, :edit, :update, :destroy]

  # GET /teamplayers
  # GET /teamplayers.json
  def index
    @teamplayers = Teamplayer.all
    @fteams = Fteam.all
    #@liveplayer = Liveplayer.all
    tid = params[:resolution]
    toimport = params[:import]

puts tid
    if tid.nil? == true
	    tid = 1
    	    @ids = tid
            @pl =  Teamplayer.joins(:live_player).where(:teamid => @ids).all
    else
	    tid = tid.to_i;
    	    @ids = tid
            @pl =  Teamplayer.joins(:live_player).where(:teamid => @ids).pluck(:Plyr, :Team)
    end
    if toimport == "true"
	    @turl = Fteam.where(:id => @ids).pluck(:TeamUrl)
  
	    @turl = @turl[0]  

    	system "rake updateTm:updateA[#{@turl},#{@ids}]"
    end


  end


  # GET /teamplayers/1
  # GET /teamplayers/1.json
  def show
  end

  # GET /teamplayers/new
  def new
    @teamplayer = Teamplayer.new
  end

  # GET /teamplayers/1/edit
  def edit
  end

  # POST /teamplayers
  # POST /teamplayers.json
  def create
    @teamplayer = Teamplayer.new(teamplayer_params)

    respond_to do |format|
      if @teamplayer.save
        format.html { redirect_to @teamplayer, notice: 'Teamplayer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teamplayer }
      else
        format.html { render action: 'new' }
        format.json { render json: @teamplayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teamplayers/1
  # PATCH/PUT /teamplayers/1.json
  def update
    respond_to do |format|
      if @teamplayer.update(teamplayer_params)
        format.html { redirect_to @teamplayer, notice: 'Teamplayer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teamplayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teamplayers/1
  # DELETE /teamplayers/1.json
  def destroy
    @teamplayer.destroy
    respond_to do |format|
      format.html { redirect_to teamplayers_url }
      format.json { head :no_content }
    end
  end

  def set_id
	  @ids = params[:resolution]
  end

  def Name_Team
	"#{Nid}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teamplayer
      @teamplayer = Teamplayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teamplayer_params
      params.require(:teamplayer).permit(:playerid, :teamid)
    end
end

app/helpers/teamplayers_helper.rb
module TeamplayersHelper
end

app/views/teamplayers/_form.html.erb
<%= form_for(@teamplayer) do |f| %>
  <% if @teamplayer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teamplayer.errors.count, "error") %> prohibited this teamplayer from being saved:</h2>

      <ul>
      <% @teamplayer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playerid %><br>
    <%= f.text_field :playerid %>
  </div>
  <div class="field">
    <%= f.label :teamid %><br>
    <%= f.text_field :teamid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teamplayers/edit.html.erb
<h1>Editing teamplayer</h1>

<%= render 'form' %>

<%= link_to 'Show', @teamplayer %> |
<%= link_to 'Back', teamplayers_path %>

app/views/teamplayers/index.html.erb
<h1>Listing teamplayers</h1>

<table>
  <thead>
    <tr>
      <th>Playerid</th>
      <th>Teamid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teamplayers.each do |teamplayer| %>
      <tr>
        <td><%= teamplayer.playerid %></td>
        <td><%= teamplayer.teamid %></td>
        <td><%= link_to 'Show', teamplayer %></td>
        <td><%= link_to 'Edit', edit_teamplayer_path(teamplayer) %></td>
        <td><%= link_to 'Destroy', teamplayer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teamplayer', new_teamplayer_path %>

app/views/teamplayers/index.js.erb
alert("Is this working");

app/views/teamplayers/new.html.erb
<h1>New teamplayer</h1>

<%= render 'form' %>

<%= link_to 'Back', teamplayers_path %>

app/views/teamplayers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Playerid:</strong>
  <%= @teamplayer.playerid %>
</p>

<p>
  <strong>Teamid:</strong>
  <%= @teamplayer.teamid %>
</p>

<%= link_to 'Edit', edit_teamplayer_path(@teamplayer) %> |
<%= link_to 'Back', teamplayers_path %>